# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/abstract_method/all/abstract_method.rbi
#
# abstract_method-1.2.1
module AbstractMethod
end
class AbstractMethodCalled < StandardError
end
class Module
  def abstract_method(*names); end
end
