# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simpleidn/all/simpleidn.rbi
#
# simpleidn-0.1.1
module SimpleIDN
  def self.to_ascii(domain, transitional = nil); end
  def self.to_unicode(domain, transitional = nil); end
  def self.uts46map(str, transitional = nil); end
  def to_ascii(domain, transitional = nil); end
  def to_unicode(domain, transitional = nil); end
  def uts46map(str, transitional = nil); end
end
class SimpleIDN::ConversionError < RangeError
end
module SimpleIDN::Punycode
  def adapt(delta, numpoints, firsttime); end
  def decode(input); end
  def decode_digit(cp); end
  def encode(input); end
  def encode_digit(d); end
  def self.adapt(delta, numpoints, firsttime); end
  def self.decode(input); end
  def self.decode_digit(cp); end
  def self.encode(input); end
  def self.encode_digit(d); end
end
