.\"
.\" Process this file with
.\"   groff -man -Tutf8 yast2.8
.\" or run
.\"   man -l yast2.8
.\" to display the man page without installing it
.\"
.\" See https://www.gnu.org/software/groff/manual/html_node/man.html#man
.\"
.TH YAST 8 "April 2021" "yast" "System configuration"
.\"
.\"
.SH NAME
YaST \- "Yet another Setup Tool", the installation and configuration tool
.\"
.\"
.SH SYNOPSIS
.B yast2 [
.I options
.B ] [
.I module
.B ] [
.I module specific options
.B ]
.\"
.\"
.SH DESCRIPTION
.B YaST
can be used to configure the system. It can configure a common hardware
(sound cards, printers), network connections (network cards), network
clients and services (like NFS, FTP), as well as general system options
(language, partitioning, software, bootloader).
.\"
.P
.B YaST
comes with
.B Qt
(graphical) and
.B ncurses
(text mode) frontends located in libyui-qt and libyui-ncurses packages. Both frontends are
functionally equivalent. The correct frontend is selected automatically based
on the available components and the current environment (the DISPLAY variable).
.\"
.P
Use
.B yast2
alone to launch the
.B YaST Control Center
from which you can select a particular configuration module or use
.B yast2
.I module
to launch the module directly.
.\"
.\"
.SH OPTIONS
.\"
.TP
.B --qt
Run YaST in the Qt graphical frontend if available, otherwise it uses the
ncurses frontend
.\"
.TP
.B --ncurses
Run YaST in the ncurses text mode frontend
.\"
.TP
.B -g, --geometry
Default window size (Qt frontend only), e.g. \fB800x600
.\"
.TP
.B -h, --help
Print usage and exit
.\"
.TP
.B -l, --list
List all available modules, to obtain usage info about
a module use
.B yast
.I module
.B help
command.
.\"
.\"
.SH COMMAND LINE INTERFACE
.TP
Some YaST modules support command line interface.
.\"
.P
To obtain a list of basic commands for using a YaST module
with support for command line interface, use:
.\"
.br
.B yast2
.I module
.B help
.br
.\"
.P
To get more comprehensive information about the commands
available for a YaST module, use:
.\"
.br
.B yast2
.I module
.B longhelp
.br
.\"
.P
To get information about the commands available for a YaST
module in a XML formatted file, use:
.\"
.br
.B yast2
.I module
.B xmlhelp
.B xmlfile=\fI<filename>\fP
.br
.\"
.P
To get information about a specific command of a YaST
module, use:
.\"
.br
.B yast2
.I module
.I command
.B help
.br
.\"
.P
To start an interactive console in which you can execute
commands of a YaST module, use
.\"
.br
.B yast2
.I module
.B interactive
.br
.\"
.\"
.SH FILES
.TP
/var/log/YaST2/*
Log files, use the
.B save_y2logs
command for saving all files into a single archive
.TP
/etc/sysconfig/yast2, $HOME/.yast2/yast2
YaST configuration files
.\"
.\"
.SH "EXIT STATUS"
.TP
.if !'po4a'hide' .B 0
Successful program execution.
.TP
.if !'po4a'hide' .B 1
Too few arguments.
.TP
.if !'po4a'hide' .B 5
Error in arguments.
.TP
.if !'po4a'hide' .B 16
Generic module error.
.TP
.if !'po4a'hide' .B > 16
Module specific error codes.
.\"
.\"
.SH AUTHOR
.nf
The YaST Team <yast-devel@opensuse.org>
.fi
.\"
.\"
.SH "SEE ALSO"
Documentation in /usr/share/doc/packages/yast2*.
.\"
.\" EOF
