#!/bin/bash

# File:		/usr/share/YaST2/bin/yast2_kde
# Module:	yast2
# Summary:	YaST2 start script for KDE
# Authors:	Klaus Kaempf <kkaempf@suse.de>
#
# $Id$
#
# This script is just like "yast2" but does _not_ set any
# geometry hints to the window manager

# load common script functions
. /usr/lib/YaST2/bin/yast2-funcs
set_qt_home_dir

# set lang from sysconfig
set_lang_from_sysconfig

# allow module as argument, defaults to "menu"
export module=${1-menu}

if [ $# == "2" ] ; then
  export arg2=($2)
  export arg3=
else
  if [ $# == "3" ] ; then
    export arg2=($2)
    export arg3=($3)
  else
    export arg3=
    export arg2=
  fi
fi

if [ "$DISPLAY" ] ; then
    set_qt_home_dir
    if [ $module == "menu" ] ; then
	$ybindir/y2controlcenter $arg2 $arg3
    else
	$ybindir/y2base $module $arg2 $arg3 qt -kcontrol_id "YaST"
    fi
fi
